<?= $this->Html->link('Help & Support', 'http://cakesf.herokuapp.com/') ?>
<?= $this->Html->link('IRC Channel', 'irc://irc.freenode.net/cakephp') ?>
<?= $this->Html->link('Issues', 'https://github.com/cakephp/cakephp/issues') ?>
<?= $this->Html->link('The Bakery', 'http://bakery.cakephp.org/') ?>
<?= $this->Html->link('Stack Overflow', 'http://stackoverflow.com/tags/cakephp') ?>
<?= $this->Html->link('Facebook Group', 'http://www.facebook.com/groups/cake.community') ?>
<?= $this->Html->link('Google+ Community', 'http://goo.gl/mSC0s') ?>
<?= $this->Html->link('YouTube Channel', 'http://www.youtube.com/user/CakePHP') ?>
<?= $this->Html->link('Follow us on Twitter', 'http://twitter.com/CakePHP') ?>
